services:
  mysql:
    image: mysql:8.0
    container_name: eventor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Thoshinny*2348
      MYSQL_DATABASE: eventregistration
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eventor-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - eventor-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - eventor-network

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventregistration
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - kafka
    networks:
      - eventor-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eventor-network

volumes:
  mysql_data:

networks:
  eventor-network:
    driver: bridge
